### PR TITLE
feat: Support mapping the vendor cache from workspace

### PR DESCRIPTION
**Pull request by russell**
It's pretty common for ruby projects to vendor their dependencies this
is to help speedup install time and is probably more useful for hybrid
projects rather than pure bazel ones that can use bazel caches.
Needless to say it's still an important feature that will make CI
faster in cases where there is no cache.

This uses some ticks saw in the nodejs rules, they use a similar mechanism to mount the node_modules into the workspace. https://bazelbuild.github.io/rules_nodejs/dependencies.html#using-bazel-managed-dependencies

for example to use this you would be required to declare it like this

```
workspace(
    name = "my_wksp",
    managed_directories = {"@bundle": ["vendor"]},
)

ruby_bundle(
    name = "bundle",
    bundler_version = "2.1.2",
    excludes = {
        "mini_portile": ["test/**/*"],
    },
    vendor_cache = True,
    gemfile = "//:Gemfile",
    gemfile_lock = "//:Gemfile.lock",
)
```

This would mount the bundle workspace directory into the run time environment, and allow bundler to use it

I'm just going to make this as a draft, but i would like feedback about if this is a reasonable approach, and if we should add tests for this case?

fixes: https://github.com/bazelruby/rules_ruby/issues/62

### CODE REVIEW

**Comment by kigster** [comment]
I like this. I suggest looking through the tests under `examples/simple` and adding a mini repo with vendored deps.

**Review by kigster — COMMENTED** [review]
I love this! Great idea and thank you for adding a working example.

One question: it is my understanding that *.gem file is just an archive with gem sources. However when the Bundler installs the gem, those that have native C-extensions will be built. Can this result in a case if eg Mac OSX binaries being "vendored" for a Linux runtime? Or are we simply talking about the sources in the *.gem files?

**Comment by russell** [comment]
> I love this! Great idea and thank you for adding a working example.
> 
> One question: it is my understanding that *.gem file is just an archive with gem sources. However when the Bundler installs the gem, those that have native C-extensions will be built. Can this result in a case if eg Mac OSX binaries being "vendored" for a Linux runtime? Or are we simply talking about the sources in the *.gem files?

You can choose, the flag's your looking for are `force_ruby_platform` or `cache_all_platforms`.  It' up you the developer if you want to vendor the prebuilt binary, but doing that will require you to add all the other platforms to your lock file.  using commands like `bundle lock --add-platform x86_64-darwin-19` and `bundle lock --add-platform x86_64-linux`.

Either way things don't fail if a gem is missing from the bundle that will only happen if you run `bundle install --local` otherwise bunder can still pull gems from remote sources I believe.  The whole point of vendoring is that it's faster than downloading the same list of gems in ephemeral environments

**Review by kigster — APPROVED** [review]
This is very good, thank you for your contribution!

**Comment by kigster** [comment]
Need to make sure that the test suite is passing.

**Comment by kigster** [comment]
Well, since it's passing! 

Congrats, and thank you once again 👍🏼

**Pull request merged**
