### PR TITLE
Fix warning due to string literal in condition

### PR DESCRIPTION
**Pull request by russell**
fixes: https://github.com/bazelruby/rules_ruby/issues/87

### CODE REVIEW

**Review by kigster — APPROVED** [review]
LGTM

**Comment by russell** [comment]
I have no write access so am unable to merge this.  Please merge when you can :)

**Comment by kigster** [comment]
Will do

**Review by kigster — APPROVED** [review]

**Comment by kigster** [comment]
Thank you for the contribution!

**Pull request merged**
