### PR TITLE
Handle absolute extension paths 

### PR DESCRIPTION
**Pull request by cpederkoff-carbon**
Require_paths is not always a relative_path. 
When it is a path to a gem extension it is given to us as an absolute path like:
`/<bazel_cache_dir>/external/bundle/lib/ruby/2.7.0/extensions/x86_64-linux/2.7.0/pg-1.0.0`
Previously this would be appended to gem_path and look like 
`lib/ruby/2.7.0/gems/pg-1.0.0/<bazel_cache_dir>/external/bundle/lib/ruby/2.7.0/extensions/x86_64-linux/2.7.0/pg-1.0.0` which does not resolve to a real file.
This new code converts that absolute path to a relative path from the expected directory and the output looks like:
`lib/ruby/2.7.0/extensions/x86_64-linux/2.7.0/pg-1.0.0`

### CODE REVIEW

**Comment by cpederkoff-carbon** [comment]
Ping @yugui @kigster it looks like CircleCI is failing on the master branch https://app.circleci.com/pipelines/github/bazelruby/rules_ruby
Not sure how to proceed.

**Comment by kigster** [comment]
I'll take a look at circle and then we can merge

**Review by kigster — APPROVED** [review]

**Comment by kigster** [comment]
Since #149 was merged, if you feel that using `cleanpath` is necessary, submit a PR that adds that.

Thanks!

**Review by kigster — CHANGES_REQUESTED** [review]
A similar PR #149 was merged.

**Pull request closed without merging**
